## NumPy and Arrays Basics

In [2]:
import numpy as np

#### Creating array from List

In [ ]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array :-> ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array ;-> ",arr_2d)

1D array :->  [1 2 3 4 5 6]
2D array ;->  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [7]:
py_list = [1,5,9]
print("Python Multiplications ",py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplications ",np_array * 2)



Python Multiplications  [1, 5, 9, 1, 5, 9]
Python array multiplications  [2 4 6]


In [12]:
import time

#operation time for List
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time ",time.time()- start)

#Operation time for Array
np_start = time.time()
np_array = np.arange(1000000) * 2
print("\n Array Operation time ",time.time()- np_start)



 List Operation time  0.1449441909790039

 Array Operation time  0.016813039779663086


### Creating Array from scratch

In [23]:
zeros = np.zeros((3,4))
print("0's array\n",zeros)

print()

ones = np.ones((2,3))
print("1's array\n",ones)

print()

#if we want array of particular value then,
full = np.full((3,2),5)
print("Full array\n",full)

print()

#If we want random number array then,
random = np.random.random((2,3))
print("Random Array\n",random)

print()

sequence = np.arange(0, 11, 2)
print("Sequence Array\n",sequence)

0's array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

1's array
 [[1. 1. 1.]
 [1. 1. 1.]]

Full array
 [[5 5]
 [5 5]
 [5 5]]

Random Array
 [[0.00429364 0.15476276 0.235266  ]
 [0.41908656 0.95527368 0.72901802]]

Sequence Array
 [ 0  2  4  6  8 10]


### Vector, Matrix, Tensor

In [27]:
vector = np.array([1,2,3,4,5])
print("Vector \n",vector)

print()

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix \n",matrix)

print()

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[10,11,12],[13,14,15]]])
print("Tensor \n",tensor)

Vector 
 [1 2 3 4 5]

Matrix 
 [[1 2 3]
 [4 5 6]]

Tensor 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape of Array ->",arr.shape)
print("Dimension of Array ->",arr.ndim)
print("Size of Array ->",arr.size)
print("Data Type ->",arr.dtype)

Shape of Array -> (2, 3)
Dimension of Array -> 2
Size of Array -> 6
Data Type -> int64


### Array Reshaping

In [55]:
arr = np.arange(12)
print("Original Array ",arr)

print()

#Reshaped array is use for shaping array
reshaped = arr.reshape((3,4))
print("Reshaped Array \n",reshaped)

print()

#if we have array in matrix format and we want in vector 
flattened = reshaped.flatten()
print("Flattened Array ",flattened)

print()

# Ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled Array ",raveled)

print()

# Transpose
transpose = reshaped.T
print("Transpose Array \n",transpose)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
