### NumPy Array Operations

In [21]:
import numpy as np

#### Array Slicing

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print("Basic Slicing ",arr[2:9])
print("Basic Slicing ",arr[2:])

print("with Step ",arr[1:8:2])

print("Negative Slicing ",arr[-5])
print("Negative Slicing ",arr[-3:])
print("Negative Slicing ",arr[-8:-2])
print("Negative Slicing ",arr[-8:-2:2])

Basic Slicing  [3 4 5 6 7 8 9]
Basic Slicing  [3 4 5 6 7 8 9]
with Step  [2 4 6 8]
Negative Slicing  5
Negative Slicing  [7 8 9]
Negative Slicing  [2 3 4 5 6 7]
Negative Slicing  [2 4 6]


In [20]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific Element ",arr_2d[2][1])
print("Entire row ",arr_2d[1])
print("Entire column ",arr_2d[:,1])


Specific Element  8
Entire row  [4 5 6]
Entire column  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([2,5,3,1,4,2,9,7,4])
print("Unsorted array ",unsorted)

#Sorted array
print("Sorted array ",np.sort(unsorted))


#Unsorted 2D Array
arr_2_unsorted = np.array([[5,3,2],
                           [7,2,6],
                           [2,3,9]])
print("Sorted 2D array by column \n",np.sort(arr_2_unsorted,axis=0))

#axis=0 is row
#axis=1 is column

Unsorted array  [2 5 3 1 4 2 9 7 4]
Sorted array  [1 2 2 3 4 4 5 7 9]
Sorted 2D array by column 
 [[2 2 2]
 [5 3 6]
 [7 3 9]]


### Filter Array

In [41]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers ",even_numbers)

Even Numbers  [ 2  4  6  8 10]


### Filter with Mask

In [43]:
mask = numbers > 5
print("Number Greater than 5 is",numbers[mask])

Number Greater than 5 is [ 6  7  8  9 10]


## Indexing and np.where()

In [ ]:
index_number = [0,2,4]
print(numbers[index_number])

where_result = np.where(numbers > 5)

# print(where_result)     Output :-> (array([5, 6, 7, 8, 9]),)
print("NP where ",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [ ]:
condition_arr1 = np.where(numbers > 5)
print(condition_arr1)

condition_arr2 = np.where(numbers > 5 , numbers*4 , numbers)
print(condition_arr2)
# reshaped = condition_arr2.reshape((2,5))
# print(reshaped)

condition_arr3 = np.where(numbers > 5 , "true" , "false")
print(condition_arr3)


'''
    How Where cluse work:

    if(condition){
    }
    else{
    }

    Here:->
    if(numbers > 5){
        numbers*4
    }else{
        number
    }

    OUTPUT :-> [ 1  2  3  4  5 24 28 32 36 40]
    Here we can clearly seen that the numver which is less than 5 it is same and 
    the number which is greater than 5 it is multiplying with 4
'''


(array([5, 6, 7, 8, 9]),)
[ 1  2  3  4  5 24 28 32 36 40]
[[ 1  2  3  4  5]
 [24 28 32 36 40]]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


'\n    How Where cluse work:\n\n    if(condition){\n    }\n    else{\n    }\n\n    Here:->\n    if(numbers > 5){\n        numbers*4\n    }else{\n        number\n    }\n\n    OUTPUT :-> [ 1  2  3  4  5 24 28 32 36 40]\n    Here we can clearly seen that the numver which is less than 5 it is same and \n    the number which is greater than 5 it is multiplying with 4\n'

### Adding and Removing Data

In [ ]:
#concatenate is used for combaine two or more array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
#arr3 = np.array([7,8,9])

combained = np.concatenate((arr1,arr2))   #OUTPUT:-> [1 2 3 4 5 6]

#combained = np.concatenate((arr1,arr2,arr3))  OUTPUT:-> [1 2 3 4 5 6 7 8 9]
print(combained)

[1 2 3 4 5 6]


### Array Compatibility

In [68]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9,10])

print("Compatibility shapes ", arr1.shape == arr2.shape)
print("Compatibility shapes ", arr1.shape == arr3.shape)

Compatibility shapes  True
Compatibility shapes  False


In [ ]:
original = np.array([[1,2],
                     [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print("Original array\n",original)
print("After adding new row\n",with_new_row)

print()

new_column = np.array([[5],[6]])
with_new_column = np.hstack((original,new_column))
print("Original array\n",original)
print("After adding new column\n", with_new_column)




Original array
 [[1 2]
 [3 4]]
After adding new row
 [[1 2]
 [3 4]
 [5 6]]

Original array
 [[1 2]
 [3 4]]
After adding new column
 [[1 2 5]
 [3 4 6]]


In [ ]:
arr1 = np.array([1,2,3,4,5])

deleted = np.delete(arr1,arr1[1:4:2])

# deleted = np.delete(arr1, 2)         # Output :-> [1 2 4 5]
# deleted = np.delete(arr1,arr1[2:4])  # Output :-> [1 2 3]
# deleted = np.delete(arr1,arr1[:4])   # Output :-> [1]

# deleted = np.delete(arr1,arr1[-1])   # This is not working this raise error IndexError
print(deleted)


#On 2D array delete value on particular place

arr2 = np.array([[1,2,3],[4,5,6]])

flatten_index = arr2.flatten()
print("Flatten index",flatten_index)

delete = np.delete(arr2,3)
print("After Deleting value",delete)

# Here we are converting 2D array into vector(Flatten Array) and after that we are 
# deleting value.

[1 2 4]
Flatten index [1 2 3 4 5 6]
After Deleting value [1 2 3 5 6]
